### ISSUE TITLE
Translation memory not saving

### ISSUE THREAD

**Issue by NightWalker77V** [URUWorks/TeroSubtitler#245] opened 2024-02-04 22:34 UTC
TM in subtitle always has been my dream and it seems like coming true! But there seems to be a problem with it here, I can not save or build a TM file so that I can recall it and use it for other and future translations. How should I do that??

**Comment by URUWorks** [comment] 2024-02-04 23:02
Several aspects must be corrected, but currently it is saved when closing the TM, loading or creating it can be done from its configuration.

**Comment by v187077924** [comment] 2024-02-05 13:00
> Several aspects must be corrected, but currently it is saved when closing the TM, loading or creating it can be done from its configuration.

Right... But the problem is even after closing it, there's still no TM file. it doesn't even create it I guess.
This happens: when I create a new TM, Click apply, Validate the lines, and close it. when I open another subtitle and want to recall the TM it's gone and these processes should be taken again and there's no sign of the previous lines that  I added to the memory, I mean that's the whole point of the TM, right? To recognize the same lines from before and use those meanings for it before or when you want to translate it.  
Or Maybe it has also do sth with the Persian language that won't save it?

**Comment by URUWorks** [comment] 2024-02-06 09:45
I just tested it and it saves it correctly, perhaps the operation needs to be modified to make it more intuitive and practical.
Maybe the file should be saved on "validate" or add an item "save"?

**Closed** 2024-03-27 10:51 UTC
